apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
spec:
  containers:
  - name: frontend-container
    image: mslee978/front
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
spec:
  containers:
  - name: backend-container
    image: mslee978/backend
    ports:
    - containerPort: 5000

---
apiVersion: v1
kind: Pod
metadata:
  name: e1db-pod
spec:
  containers:
  - name: e1db-container
    image: mslee978/e1db
    ports:
    - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  - protocol: TCP
    port: 5000
    targetPort: 5000
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: LoadBalancer
